# Generated by Django 6.0.6 on 2026-06-25 04:23

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_default_roles_and_admin(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    User = apps.get_model("auth", "User")

    admin_group, _ = Group.objects.get_or_create(name="Администратор")
    buyer_group, _ = Group.objects.get_or_create(name="Покупатель")

    admin_user, created = User.objects.get_or_create(
        username="admin",
        defaults={
            "email": "admin@example.com",
            "password": make_password("admin"),
            "is_staff": True,
            "is_superuser": True,
            "is_active": True,
        },
    )

    if not created:
        admin_user.email = admin_user.email or "admin@example.com"
        admin_user.is_staff = True
        admin_user.is_superuser = True
        admin_user.is_active = True
        admin_user.save(update_fields=["email", "is_staff", "is_superuser", "is_active"])

    admin_user.groups.add(admin_group)


def delete_default_roles_and_admin(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    User = apps.get_model("auth", "User")

    User.objects.filter(username="admin", email="admin@example.com").delete()
    Group.objects.filter(name__in=["Администратор", "Покупатель"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_roles_and_admin, delete_default_roles_and_admin),
    ]
