# Generated by Django 6.0.6 on 2026-06-25 04:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('express_delivery_price', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10, verbose_name='стоимость экспресс-доставки')),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=10, verbose_name='порог бесплатной обычной доставки')),
                ('standard_delivery_price', models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=10, verbose_name='стоимость обычной доставки до порога')),
            ],
            options={
                'verbose_name': 'настройки доставки',
                'verbose_name_plural': 'настройки доставки',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='ключ сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'корзины',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='удалён')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='дата удаления')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Ф. И. О.')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='телефон')),
                ('delivery_type', models.CharField(choices=[('ordinary', 'Обычная доставка'), ('express', 'Экспресс-доставка')], default='ordinary', max_length=20, verbose_name='способ доставки')),
                ('payment_type', models.CharField(choices=[('online', 'Онлайн картой'), ('someone', 'Онлайн со случайного чужого счёта')], default='online', max_length=20, verbose_name='способ оплаты')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='город')),
                ('address', models.TextField(blank=True, verbose_name='адрес')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий к заказу')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='общая стоимость')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='стоимость доставки')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('accepted', 'Подтверждён'), ('paid', 'Оплачен'), ('payment_error', 'Ошибка оплаты')], default='created', max_length=30, verbose_name='статус')),
                ('payment_error', models.TextField(blank=True, verbose_name='ошибка оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255, verbose_name='название товара на момент заказа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена на момент заказа')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'товар в заказе',
                'verbose_name_plural': 'товары в заказе',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8, verbose_name='номер карты/счёта')),
                ('status', models.CharField(choices=[('waiting', 'Ожидает подтверждения'), ('success', 'Оплата подтверждена'), ('error', 'Ошибка оплаты')], default='waiting', max_length=20, verbose_name='статус')),
                ('error', models.TextField(blank=True, verbose_name='текст ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'платёж',
                'verbose_name_plural': 'платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='количество')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.basket', verbose_name='корзина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='shop.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'товар в корзине',
                'verbose_name_plural': 'товары в корзине',
                'unique_together': {('basket', 'product')},
            },
        ),
    ]
