# Generated by Django 6.0.6 on 2026-06-25 04:24

from decimal import Decimal

from django.db import migrations


def create_delivery_settings(apps, schema_editor):
    DeliverySettings = apps.get_model("orders", "DeliverySettings")

    DeliverySettings.objects.get_or_create(
        pk=1,
        defaults={
            "express_delivery_price": Decimal("500.00"),
            "free_delivery_threshold": Decimal("2000.00"),
            "standard_delivery_price": Decimal("200.00"),
        },
    )


def delete_delivery_settings(apps, schema_editor):
    DeliverySettings = apps.get_model("orders", "DeliverySettings")
    DeliverySettings.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_delivery_settings, delete_delivery_settings),
    ]
